docs/compiling-coreboot.md
Fedora had me install the `openssl`, `libuuid-devel`, and `nasm` packages to build coreboot
=> Add build dependencies to fedora

docs/faq.md
This pr was made to change the ["Can I get AVS or SOF drivers for free?"](https://chrultrabook.github.io/docs/docs/faq.html) faq section to avoid implying that all AVS or SOF drivers are not free but bring up that only the Linux drivers are free.
=> change wording in "Can I get AVS or SOF drivers for free?"

docs/post-install.md
This updates the [keyboard layout](https://github.com/chrultrabook/docs/blob/main/docs/post-install.md#linux) link from the original repo to the [chrultrabook repo](https://github.com/chrultrabook/keydconfig) due to the old repo getting removed.
=> change keyboard layout link

docs/unbricking.md
This pr was made to fix the missing dot when referencing Ubuntu 23.04 and also finishes a sentence in [unbricking.md](https://github.com/chrultrabook/docs/blob/main/docs/unbricking.md).
=> fix ubuntu versioning and punctuation in unbricking.md

docs/system-info.md
This pr fixes the formatting of the new [system-info](https://github.com/chrultrabook/docs/blob/b110dcbd0e429eaa60aa335903a8f444cf33ef13/docs/system-info.md?plain=1#L7) note so that it displays correctly
=> Fix system-info.md note

docs/post-install.md
This seems to be the equivalent of "useplatformclock true" as it forces use of the HPET timer. For one user, switching to HPET has shown to be effective in fixing crashes in applications such as Parsec. Additionally, it may have fixed another user's stuttering issues.
Here are some sources from the chultrabook Discord server that have shown success following these steps:
[https://discord.com/channels/232609321274310656/232609321274310656/1141805003258986597](url)
[https://discord.com/channels/232609321274310656/1033119537656234097/1150696423734640730](url)
Going by these, I'm confident that these parameters do have a positive effect on this device, and that we should add them to the docs for others to experiment with them.
=> Add Linux workaround instructions for CELES

docs/post-install.md
Since the [keydconfig](https://github.com/chrultrabook/keydconfig) repo is archived and links to the newer version, point to the newer version instead of the old one.
=> add cros-keyboard-map script

docs/installing-macos.md
Not happy with the formatting, but not really sure how to make it better. Feel free to comment suggestions/make edits directly.
This adds a new kexts (CrosEC) and switches out VoodooPS2 with my fork. It also adds a couple of SSDTs for mapping the keyboard and adding a fake ALS (which fixes some backlight functionality as well as keyboard backlight). I removed the two SSDTs to disable devices, as macOS does not power down PCIe devices which are disabled in ACPI. These effectively break functionality (like HDMI audio) without reducing power usage.
=> [macOS] Add new kexts, remove unneeded SSDTs

docs/bootableusb.md, docs/faq.md, docs/installing-linux.md
This PR updates the docs about the situation of Ubuntu and adds a custom kernel warning for Debian in [installing-linux.md](https://github.com/chrultrabook/docs/blob/main/docs/installing-linux.md)
=> Change Ubuntu warning + add custom kernel warning for debian

docs/distros.md
I believe that using `fetchurl` is very cumbersome, since `fetchFromGitHub` already exists and the source is already a GitHub repo. It also causes weird problems that I can't quite figure out when you try to update to a later commit. By using `fetchFromGitHub` instead, updating just means you need to update the rev and hash. This also has the added benefit of not needing to override `unpackPhase` at all.
I've also decided to move the WeirdTreeThing repo sources off to a different variable `wttsrc` instead of trying to override `src` or create a new variable `srcs`. This makes the intent of the overlay clearer and lets the alsa-ucm-conf tarball defined in `src` update independently of the overlay.
=> docs/distros.md: cleaner nixpkgs overlay

supported-devices/devices.json, supported-devices/template.md
Supplements commit a38ed64 by WeirdTreeThing with latest info referenced from https://coolstar.org/chromebook/windows.html
Reiterate booting from eMMC is not supported on AMD Picasso devices in the Windows Notes column (please advise if this can be worded better, much appreciated thanks!)
Remove outdated info about Ryzen needing RWL hack
=> Further update to support notes for AMD Ryzen

src/docs/firmware/battery.md
Since on some chromebooks you can pry the back off, you have to remove the battery. So I simply added a bullet point.
=> Added keyboard prying

src/docs/unbricking/index.md
It was there since the page originally used bolded text for headers, and was probably left there as an artifact due to an accident.
=> Remove accidental bold trace in unbricking/index.md

src/docs/firmware/flashing-firmware.md, src/docs/installing/installing-linux.md
When following the guide using `RW_LEGACY` firmware on my Chromebook, I was met with a white "Additional Firmware Menu" blank screen after pressing `CTRL` + `L`. It was unclear where to go from here if this occurs. You simply need to press 0 for internal storage boot or 2 for USB boot. This left me confused as it is not mentioned in the docs.
I have added a TIP on installing linux on how to boot this way, along with further information under "Flashing firmware" -> "RW_LEGACY" at the bottom of the page.
=> Clarified how to boot from RW_LEGACY

src/docs/faq.md
This PR moves instructions on how to exit dev mode when dev mode is force enabled via GBB flags from the current `src/docs/exiting-developer-mode.md` into the FAQ, as it isn't currently visible on the docs site and I couldn't think of a good place to put it in the current docs hierarchy. 
In moving the content over, I've taken the liberty of attempting to simplify the instructions. Please confirm that the command I've specified (using crossystem to disable developer mode) is indeed universal to all Chromebooks/Chromeboxes/Chromeblets etc - it's been a while since I've personally been on ChromeOS :)
=> Move "exiting developer mode" content to faq.md

src/docs/installing/distros.md
The WTT keyd script added more ids so the nix config should too. I 'm pretty sure the other ids are for detachable and weird devices.
=> Add additional keyboard ids

supported-devices/devices.json
Updated info for SARIEN Chromebook.
Full UEFI is not supported in this Chromebook, but everything I tested works under RW_Legacy firmware with Linux Mint 22.3.
This Chromebook has upgradable RAM and SSD, but I am not sure whether that too should be added to the notes.
=> Updated info for SARIEN

src/docs/firmware/ti50-ap-ro.md, src/docs/firmware/write-protect.md, src/docs/unbricking/index.md
This PR includes the following things for PR #159.
- Changing the Ti50 inclusion in write-protect.md to a warning since this feels like something the reader should watch out for.
- Adding Chromebox and Tablet recovery sections in ti50-ap-ro.md.
- Referencing it in unbricking/index.md
=> Add additional things to the Ti50 AP FW RO verification PR

src/docs/firmware/ti50-ap-ro.md, src/docs/firmware/write-protect.md, src/docs/unbricking/index.md
=> Add Ti50 AP FW RO verification page

src/docs/unbricking/index.md
The `MD003` heading style consistency error is caused by the (accidental) placement of a horizontal rule directly below a line of text, turning that text into a heading, which wasn't the intention.
=> Solve markdown linter errors specific to #159

supported-devices/devices.json
All Chromium docs links in devices.json give 404, as the upstream links seemed to have changed. These are the proper links.
=> Fix chromium links

src/docs/faq.md, src/docs/installing/installing-linux.md
- Remove Debian from recommendations since its age starts to show
- Remove exaggerations about Ubuntu
- Generalize prior Debian warnings to old LTS releases in general
=> (RFC) reword LTS warnings and notes

src/docs/firmware/about.md
=> Fix a typo in Types of Firmware page (firmware/about.md)

src/docs/installing/post-install.md
This adds Debian/Ubuntu instruction for rebuilding the initramfs  to fix the `cros_ec_typec` loading issue as also appears in Fedora.
=> Update post-install.md to add Debian/Ubuntu instructions for USB-C fixes
