_config.yml, docs/altos.md, docs/firmware.md, docs/getting-started.md, docs/installing-linux.md, docs/installing-macos.md, docs/installing-windows.md, docs/prerequisites.md, docs/supported-devices.md, index.md
- Use theme's "warning" theme
- Fix a bunch of styling
=> Fix styling 

docs/csdriver.md, docs/signedlicense.md
=> Fix broken images introduced in the previous PR

docs/altos.md, docs/compiling-coreboot.md, docs/known-issues.md, docs/supported-devices.md
I fixed issues and moved some things around pls accept
=> docs? better

docs/contributing.md
=> Created a page for contributing  

docs/post-install.md, docs/supported-devices.md
This pr adds the notes section, from https://mrchromebox.tech/#devices, as well as the CELES post install script (instead of linking to a deleted post)
I'm really bad at writing docs most of the time, so if anything needs to be changed, let me know!
=> Add "notes" section from https://mrchromebox.tech/#devices

docs/installing-windows.md
=> Make coolstar windows helper link show text instead of a url

docs/firmware.md
=> Clarify step #4 in firmware.md; closes #45

docs/compiling-coreboot.md
Add packages imagemagick nasm python-is-python3 uuid-dev
=> Extend list of required Debian packages for building coreboot

docs/csdriver.md
Closes #48 
Adds a note explaining how you can buy more than 1 driver at a time.
=> Added note on how to custom pledge (thx @ethanaobrien)

docs/signedlicense.md
This update adds the following:
-2 additional warnings telling the user to unsubscribe from CS Patreon in signedlicense.md
=> 08.17.2023 update

docs/faq.md
This pr adds the specific cpus eligible for a discount. [See](https://discordapp.com/channels/232609321274310656/233686891701075968/1141436557702738040)
This also adds instructions into the faq on how to change fan speeds through `ectool`, since that seems to be asked frequently.
=> Add specifics to bulk discount/add faq for changing fan speeds

docs/installing-macos.md, docs/supported-devices.md, docs/system-info.md
Changes no html, just cleans it up so it doesnt look poopy, and makes it easier to edit in the future
=> Cleanup supported devices table

docs/installing-linux.md
=> "newer" not "newner"

docs/supported-devices.md
Fixes linux chart in supported devices
This was an absolute pain to do
=> Fix supported linux chart

assets/css/just-the-docs-switchable.css, docs/installing-macos.md, docs/post-install.md, docs/supported-devices.md
=> Add windows/macos/linx support/notes to table

docs/system-info.md
The commands require [Developer Mode](https://chromium.googlesource.com/chromiumos/docs/+/HEAD/developer_mode.md) to be enabled.
=> add developer mode note to system-info.md

docs/supported-devices.md
- Touchpad is no longer bad (after workarounds)
- No fixes for camera as of now
=> Update redrix issues

docs/supported-devices.md, supported-devices/index.js, supported-devices/template.md
Fixes the note comment style because I forgot markdown uses html styled comments.
Fixes the template supported devices being shown in the menu thingy
=> Minor fixes

docs/reverting.md
A lot of people needed to unplug the battery for recovery to work.
=> (reverting.md) Add Unplugging Battery Part

docs/altos.md, docs/bootableusb.md, docs/getting-started.md, docs/installing-linux.md, docs/installing-windows.md, docs/supported-devices.md, docs/unbricking.md, docs/ventoy.md, index.md
this just makes it easier for newcomers, and non-english speakers to understand
please tell me if i got something wrong, of if i deleted too much
=> Lowered the reading level, and simplified some things

docs/bootableusb.md
I mainly did this for Ventoy to bring up the fact that you can add more ISO's to it.
=> (bootableusb.md) Add blurb for Rufus and Ventoy

docs/advanced.md, docs/bootableusb.md, docs/bugreport.md, docs/compiling-coreboot.md, docs/contributing.md, docs/debugging.md, docs/distros.md, docs/faq.md, docs/firmware.md, docs/reverting.md, docs/unbrick-flipper.md, docs/unbricking.md, docs/updating-firmware.md, docs/ventoy.md
Separate flashing fw and updating fw
Fix a typo
Add linux keyboard remap info to faq
=> Minor improvements and fixes

src/docs/ectool.md
Added the ectool common usage and guide
=> ectool guide and usage 🛠️

src/docs/firmware/developer-mode.md, src/docs/unbricking/index.md
im currently reading the whole documentation. Please do not merge until ALL spelling or grammar errors have been fixed. Thank you.
=> Some grammar/spelling errors.

CNAME, src/.vuepress/config.js
After this is good to go @coolstar can you add the entry in Cloudflare
thanks
=> Create CNAME file for custom domain

src/.vuepress/config.js
This reverts commit 60b36b1e92b535fd4d701a7e1ed1a6ef1bd677e6.
=> Revert "Update config.js"

src/.vuepress/config.js, src/docs/firmware/battery.md, src/docs/firmware/developer-mode.md, src/docs/firmware/manually-flashing.md, src/docs/firmware/write-protect.md
**DO NOT MERGE THE WEBSITE IS BROKEN AS SHIT RIGHT NOW**
=> Fix capitalization consistency 

supported-devices/devices.json
Guess how I know JELBOZ360 is supported?;)
Also improve consistency across device names, in particular the word salad that is HP Chromebooks
=> Add JELBOZ360 to supported devices

src/docs/faq.md, src/index.md, supported-devices/template.md
this is for the grammar related stuff. 
context: #133 
tree im not a web dev :/
=> redoing last pr pretty much #133

src/docs/faq.md, src/docs/installing/bootableusb.md, src/docs/installing/index.md, src/docs/installing/installing-linux.md, src/docs/unbricking/unbrick-ch341a.md, src/docs/unbricking/unbrick-suzyq.md
=> Strike Ubuntu from recommendations

supported-devices/devices.json
=> Note that mic is not supported on cyan in windows

package-lock.json, package.json, src/.vuepress/config.js, src/.vuepress/public/robots.txt
=> SEO Optimisations

supported-devices/devices.json
Yay amd finally fixed headphones!!!
=> supported-devices: Update mdn linux note

src/docs/firmware/known-issues.md, supported-devices/devices.json
=> Picasso eMMC is now supported in edk2

src/docs/faq.md
Fix regression introduced in 0456ceb
=> faq.md: Fix HTML comment tag

src/.vuepress/config.js, src/docs/installing/distros.md
The replacement is intended to help advanced users find what they need to get their distro of choice to work properly
=> Replace distos specifics page with a simple Note page

src/.vuepress/config.js
=> Fix docs sidebar (do not auto display links for headers)

src/.vuepress/config.js
Sorry I changed the wrong property.
=> Fix #196 mistake

package-lock.json, package.json
`npx npm-check-updates -u -t newest`
=> bump dependencies in package.json

src/.vuepress/config.js
Proposal for discussion.
List of supported devices is pretty useless if i don't know which I've got
=> Page order: Finding System Info -> Supported Devices

package-lock.json, src/docs/firmware/index.md, src/docs/firmware/known-issues.md, src/docs/firmware/system-info.md, supported-devices/template.md
Follow up fixes for #201 regarding button links
=> Follow-up: Finding System Info -> Supported Devices

src/docs/unbricking/unbrick-flipper.md
change unbricked to bricked as it previously did not make sense
=> [unbrick-flipper.md] change unbricked to bricked

src/docs/firmware/compiling-coreboot.md
=> fix build script output folder
